id: P000374
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W28261
  title: སུམ་རྟགས་ཀྱི་འགྲེལ་པ་ཨུཏྤ་ལ་ཡི་རྣ་རྒྱན།
  author: ''
  volumes:
    28fe6995a1f04150935c5161fe1ce7c2:
      image_group_id: I1KG12874
      title: Volume 1 of sum rtags kyi 'grel pa ut+pa la yi rna rgyan/
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
