id: I1DEDE651
legacy_id: P000374
ocr_import_info:
  bdrc_scan_id: W28261
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T10:14:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:18:18.983316+00:00'
last_modified: 2022-09-02 16:18:44.042173
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28261
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW28261
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སུམ་རྟགས་ཀྱི་འགྲེལ་པ་ཨུཏྤ་ལ་ཡི་རྣ་རྒྱན།
  author: རྡོ་རིང་བསྟན་འཛིན་དཔལ་འབྱོར།
statistics:
  ocr_word_mean_confidence_index: 0.7025888012434137
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I1KG12874:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12874
      total_pages: 156
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12874.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.7025888012434137
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
